"""initial schema

Revision ID: e0f7d31fa838
Revises: 
Create Date: 2026-08-13 01:36:20.746015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f7d31fa838'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('google_tokens_encrypted', sa.Text(), nullable=True),
    sa.Column('drive_folder_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)

    op.create_table('custom_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=64), nullable=True),
    sa.Column('verification_method', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_domains_domain'), ['domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_custom_domains_user_id'), ['user_id'], unique=False)

    op.create_table('qr_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('destination_url', sa.Text(), nullable=True),
    sa.Column('google_drive_file_id', sa.String(length=255), nullable=True),
    sa.Column('google_drive_folder_id', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('custom_domain_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['custom_domain_id'], ['custom_domains.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qr_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qr_links_short_code'), ['short_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_qr_links_user_id'), ['user_id'], unique=False)

    op.create_table('scan_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr_link_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=200), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['qr_link_id'], ['qr_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_events_ip_hash'), ['ip_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_events_qr_link_id'), ['qr_link_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_events_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_scan_events_qr_link_id'))
        batch_op.drop_index(batch_op.f('ix_scan_events_ip_hash'))

    op.drop_table('scan_events')
    with op.batch_alter_table('qr_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qr_links_user_id'))
        batch_op.drop_index(batch_op.f('ix_qr_links_short_code'))

    op.drop_table('qr_links')
    with op.batch_alter_table('custom_domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_domains_user_id'))
        batch_op.drop_index(batch_op.f('ix_custom_domains_domain'))

    op.drop_table('custom_domains')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
